### PR TITLE
Dcokerfile: Install cpio

### PR DESCRIPTION
**Pull request by Forenche**
Dependency required for 4.19+ kernels. Also indent the code a bit.

### CODE REVIEW

**Comment by SakthivelNadar** [comment]
ohooo pru gawd

**Comment by starlight5234** [comment]
Acha

**Comment by SakthivelNadar** [comment]
> Acha

yes sar

**Comment by sohamxda7** [comment]
> Dependency required for 4.19+ kernels. Also indent the code a bit.

very pro

**Comment by starlight5234** [comment]
> Dependency required for 4.19+ kernels. Also indent the code a bit.

Sir how to become gawd like you?

**Comment by Forenche** [comment]
What in tarnation...

**Pull request merged**
