### PR TITLE
Dockrerfile: Install wget

### PR DESCRIPTION
**Pull request by Forenche**
Needed for fetching build scripts

### CODE REVIEW

**Comment by starlight5234** [comment]
curl use kar lavde

image

**Comment by Forenche** [comment]
> curl use kar lavde
> 
> image

Omkay God :(

**Comment by starlight5234** [comment]
> Omkay God :(

Merge karu kya?

**Comment by Forenche** [comment]
> > Omkay God :(
> 
> Merge karu kya?

upto you, I edited my build script to install wget tho

**Pull request merged**
